### ISSUE TITLE
Facebook plugin does not reload

### ISSUE THREAD

**Issue by viridis** [RoelandMatthijssens/bazingaWebsite#8]
Once you go to a contact, wait for the facebook plugin to load, then go to another page, and then back to the contact page, the facebook plugin will not reload.

**Comment by Jeroen-Matthijssens** [comment]
This seems to be specific to the facebook script. The javascript for google maps reloads just fine. The script for facebook does  complain about an id not being numeric. It's just a waring but still.

```
Invalid App Id: Must be a number or numeric string representing the application id.
```

[this site](http://developwithguru.com/solve-invalid-app-id-must-be-a-number-or-numeric-string-representing-the-application-id/) give a solution if this is our problem.
